CREATE TABLE IF NOT EXISTS "app_relawan_MsUser" (
	"UserId" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_relawan_MsUser_UserId_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Email" varchar(50) NOT NULL,
	"Username" varchar(25) NOT NULL,
	"Password" varchar(50) NOT NULL,
	CONSTRAINT "app_relawan_MsUser_Email_unique" UNIQUE("Email"),
	CONSTRAINT "app_relawan_MsUser_Username_unique" UNIQUE("Username")
);
